version: '3.8'
services:
  db:
    image: postgres:14-alpine
    container_name: postgres-db
    environment:
      - POSTGRES_DB=gestaoDeProjeto
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./Back-end
      dockerfile: Dockerfile
    container_name: springboot-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-vite-frontend
    ports:
      - "3000:80"  
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
